spring:
  application:
    name: gateway-api
server:
  port: 8765
zuul:
  routes:
    auth-server:
      path: /auth-api/**
      sensitiveHeaders: Cookie,Set-Cookie
      service-id: auth-server
      strip-prefix: true
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
ribbon:
  ReadTimeout: 5000